enhancement:
  - src/main/**
  - !src/main/resources/lib/**

test:
  - src/test/**

workflow:
  - .github/**

documentation:
  - LICENSE
  - README.md

dependencies:
  - pom.xml
  - src/main/resources/lib/**
