enhancement:
  - any: [ 'src/main/**', '!src/main/resources/lib/**' ]

test:
  - src/test/**

workflow:
  - .github/**

documentation:
  - LICENSE
  - README.md
  - CONTRIBUTORS.md

dependencies:
  - pom.xml
  - src/main/resources/lib/**

automerge:
  - all: [ 'README.md' ]
  - all: [ '.github/**' ]
  - all: [ 'CONTRIBUTORS.md' ]
